### ISSUE TITLE
도메인끼리 언제 연동할까요 ?

### ISSUE THREAD

**Issue by seu1a** [ducami-org/ducademi-server#21]
이번주에 도메인별로 기초적인 CRUD가 끝났습니다.

게시글 같은 경우는 작성자와 멤버를 연동하는 것처럼
도메인끼리 연동이 필요한 로직이 있습니다

그래서 오늘 10, 11교시에 전체적으로 
연동이 필요한 것끼리 한번에 하는게 어떨까 싶은데
다들 어떻게 생각하실지 궁금합니다.

만약 괜찮으시다면 연동이 필요한 것들을 함께 적어주셨으면 좋겠습니다. 👍 👍
기타 의견도 좋습니다

**Comment by alexipharmical** [comment]
저는 멤버랑 강의 부분 연결해야 합니다!

**Comment by whitenoise13** [comment]
교재랑 저자 연결해야 해요

**Comment by seu1a** [comment]
좋습니다. 해결되었습니다. ✅
