### ISSUE TITLE
JWT 클레임에 어떤 정보를 담을까요 ?

### ISSUE THREAD

**Issue by seu1a** [ducami-org/ducademi-server#3]
현재 회원가입 로직 완성되었고 로그인 로직을 짜고 있는데
JWT 안에 어떤 정보들이 필요할까요 ㅜㅜ
유저 PK와 권한만 있으면 충분할까요 ?

**Comment by heunseoRyu** [comment]
{
  "sub": "",
  "authority": "",
  "iat":,
  "exp":
} 저는 이렇게 했어요 : D

**Comment by seu1a** [comment]
감사합니다 😊
그러면 유저 PK와 권한, 그리고 발급일, 만료일 넣도록 하겠습니다
👍 👍

**Comment by seu1a** [comment]
이슈 다시 열어서 죄송합니다 ㅜ
유저 PK 대신 이메일을 넣어야 할 것 같아요
이렇게 해도 괜찮을까요 ?

**Comment by whitenoise13** [comment]
유저 PK대신에 이메일 넣어도 문제는 없을 거 같아요
