### ISSUE TITLE
전체 CORS 설정 누가 할까요 ?

### ISSUE THREAD

**Issue by seu1a** [ducami-org/ducademi-server#54]
제가 영우랑 테스트를 하다가 교차 출처 문제가 발생하여
임시로 멤버 컨트롤러에 CORS 애노테이션을 붙여 설정을 해두었는데
모든 컨트롤러에 애노테이션을 붙이기 보단
저희는 스프링 시큐리티를 사용하기 때문에
SecurityConfig에서 CORS를 설정하는 편이 좋을 것 같습니다

그래서 담당을 정하고 진행하는 편이 좋을 것 같습니다

**Comment by heunseoRyu** [comment]
제가 팀장이니 하겠습니당

**Comment by seu1a** [comment]
옙 알겠습니다 😊
