### ISSUE TITLE
구글로 회원가입 시 받아오지 못하는 정보는 어떻게 처리할까요 ?

### ISSUE THREAD

**Issue by seu1a** [ducami-org/ducademi-server#8]
아래 정보는 사용자가 공개로 설정하지 않으면 받아올 수 없습니다

- **실명**
- **생일**
- **전화번호**

그럼 저희가 할 수 있는 건 크게 두가지라고 생각합니다

1. OAuth2를 통해 회원가입 후 실명, 생일, 전화번호를 입력하는 뷰로 리다이렉트
2. 필드에 공백을 넣고 추후 사용자의 옵션으로 실명, 생일, 전화번호를 수정하게 하기

1번은 서버가 OAuth2로 로그인 시 **비어있는 필드가 있는지 확인하여 있다면 입력을 강제** 할 수 있습니다
2번은 강제하지 않고 **사용자가 자율적으로 수정**할 수 있다는 차이가 있습니다

여러분의 생각은 어떠신가요 ?

**Comment by seu1a** [comment]
관련 이슈 )
#6 #7

**Comment by heunseoRyu** [comment]
1번 어떤가요? 변수가 훨씬 줄어들 듯 합니다

**Comment by alexipharmical** [comment]
굳이 강제할 필요 있나요? 마땅한 이유가 없다면 2번이 낫다고 생각합니다.

**Comment by seu1a** [comment]
@whitenoise13 의견 부탁드립니다 👋

**Comment by whitenoise13** [comment]
개인적으로 추후 수정보다는 처음부터 잘 받아놓는게 더 좋다고 생각해서 1번이 더 나을 듯 합니다

**Comment by seu1a** [comment]
서버에서 OAuth2 클라이언트를 구현하면 웹은 인증 후
스프링이 해당 토큰을 사용하여 사용자의 정보를 자동으로 불러오지만
모바일 같은 경우는 웹뷰를 띄우지 않는 이상
자동으로 서버로 토큰이 전송되지 않는 걸로 알고 있습니다

이 부분은 따로 이슈를 생성하도록 하겠습니다
